package com.example.localization

import com.example.model.AppLanguage

object AppStrings {

    fun get(key: String, lang: AppLanguage): String {
        val strings = when (lang) {
            AppLanguage.FA -> faStrings
            AppLanguage.EN -> enStrings
        }
        return strings[key] ?: enStrings[key] ?: key
    }

    private val faStrings = mapOf(
        "app_name" to "ReNo VPN (رنو وی‌پی‌ان)",
        "app_subtitle" to "سریع، امن و پرقدرت",
        "tap_to_connect" to "لمس برای اتصال",
        "tap_to_disconnect" to "قطع اتصال",
        "connecting" to "در حال اتصال...",
        "disconnecting" to "در حال قطع...",
        "connected" to "متصل شد",
        "disconnected" to "قطع شد",
        "status_secure" to "اتصال امن و رمزنگاری شده",
        "status_not_connected" to "اتصال شما حفاظت نشده است",
        "select_server" to "انتخاب سرور",
        "optimal_server" to "سرور هوشمند و پرسرعت",
        "upload_speed" to "سرور آپلود",
        "download_speed" to "سرور دانلود",
        "upload" to "آپلود",
        "download" to "دانلود",
        "total_upload" to "مجموع آپلود",
        "total_download" to "مجموع دانلود",
        "connection_time" to "مدت زمان اتصال",
        "ping" to "پینگ",
        "ms" to "میلی‌ثانیه",
        "virtual_ip" to "آی‌پی مجازی",
        "protocol" to "پروتکل",
        "settings" to "تنظیمات",
        "language" to "زبان برنامه (Language)",
        "persian" to "فارسی",
        "english" to "English",
        "kill_switch" to "کیل‌سوئیچ (قطع اینترنت اضطراری)",
        "kill_switch_desc" to "قطع کل ترافیک در صورت قطع ناگهانی وی‌پی‌ان",
        "split_tunneling" to "تفکیک ترافیک (Split Tunneling)",
        "split_tunneling_desc" to "عدم عبور سایت‌ها و اپلیکیشن‌های ایرانی از فیلترشکن",
        "dns_settings" to "تنظیمات دی‌ان‌اس (DNS)",
        "auto_connect" to "اتصال خودکار هنگام باز شدن برنامه",
        "admin_panel" to "پنل مدیریت اختصاصی",
        "admin_panel_desc" to "مدیریت و وارد کردن کانفیگ‌ها و سرورها",
        "admin_locked_tip" to "جهت ورود به پنل مدیریت رمز عبور را وارد کنید",
        "enter_pin" to "ورود پین کد مدیریت",
        "pin_placeholder" to "پین ۴ رقمی (پیش‌فرض: ۱۲۳۴)",
        "unlock" to "ورود به پنل",
        "cancel" to "انصراف",
        "wrong_pin" to "رمز عبور نادرست است!",
        "admin_title" to "پنل مدیریت کانفیگ‌ها",
        "add_new_config" to "افزودن کانفیگ جدید",
        "import_clipboard" to "دریافت از کلیپ‌بورد",
        "config_name" to "نام سرور / کانفیگ",
        "config_name_hint" to "مثال: سرور آلمان پرسرعت",
        "config_url" to "لینک یا کد کانفیگ (VLESS/VMESS/SS/Trojan)",
        "config_url_hint" to "vless://... یا vmess://... یا ss://...",
        "country" to "کشور",
        "flag" to "پرچم",
        "protocol_type" to "نوع پروتکل",
        "expiration_date" to "تاریخ انقضا (روز)",
        "save_config" to "ذخیره کانفیگ",
        "edit_config" to "ویرایش کانفیگ",
        "delete" to "حذف",
        "delete_confirm" to "آیا از حذف این کانفیگ مطمئن هستید؟",
        "test_ping" to "تست پینگ همه",
        "active_configs" to "کانفیگ‌های فعال",
        "no_configs" to "هنوز کانفیگی ثبت نشده است. می‌توانید با دکمه بالا اضافه کنید.",
        "config_added_success" to "کانفیگ با موفقیت ذخیره شد",
        "config_deleted" to "کانفیگ حذف شد",
        "expired" to "منقضی شده",
        "active" to "فعال",
        "change_admin_pin" to "تغییر پین مدیریت",
        "new_pin" to "پین کد جدید",
        "save_pin" to "ذخیره پین",
        "pin_changed" to "پین کد با موفقیت تغییر یافت",
        "secret_unlock_hint" to "دسترسی ویژه مدیر فعال شد!",
        "about" to "درباره برنامه",
        "about_text" to "رنو وی‌پی‌ان (ReNo VPN)، ابزاری مدرن با قابلیت ضدسانسور، تست سرعت زنده و قابلیت مدیریت کانفیگ توسط ادمین.",
        "version" to "نسخه ۱.۰.۰",
        "reset_defaults" to "بازیابی سرورهای پیش‌فرض",
        "speed_live" to "مانیتور ترافیک زنده",
        "all_servers" to "همه لوکیشن‌ها",
        "vip_servers" to "سرورهای اختصاصی",
        "custom_servers" to "سرورهای ادمین",
        "auto_select" to "انتخاب خودکار (هوشمند)",
        "auto_select_desc" to "اتصال خودکار به خلوت‌ترین سرور با بالاترین سرعت",
        "antenna_green_desc" to "ترافیک خلوت (سبز - اتصال پرسرعت)",
        "antenna_yellow_desc" to "ترافیک متوسط (زرد - ۲ آنتن)",
        "antenna_red_desc" to "ترافیک شلوغ (قرمز - ۱ آنتن)",
        "server_locked_title" to "سرور قفل است (VIP)",
        "server_locked_msg" to "این کشور در نسخه عادی قفل است. در حال حاضر اتصال از طریق «انتخاب خودکار» به صورت پرسرعت و رایگان فعال است.",
        "locked" to "قفل",
        "unlocked" to "آزاد",
        "users_online" to "کاربر آنلاین",
        "simulate_load" to "تغییر وضعیت ترافیک سرور",
        "traffic_status" to "وضعیت بار شبکه",
        "security_level" to "رمزنگاری ترافیک",
        "security_value" to "AES-256 + TLS",
        "kb_s" to "کیلوبایت/ثانیه",
        "mb_s" to "مگابایت/ثانیه",
        "latency_good" to "عالی",
        "latency_medium" to "متوسط",
        "latency_poor" to "ضعیف",
        "secret_tap_hint" to "۵ بار لمس لوگو برای باز کردن پنل مدیریت"
    )

    private val enStrings = mapOf(
        "app_name" to "ReNo VPN",
        "app_subtitle" to "Fast, Secure & Unlimited",
        "tap_to_connect" to "Tap to Connect",
        "tap_to_disconnect" to "Disconnect",
        "connecting" to "Connecting...",
        "disconnecting" to "Disconnecting...",
        "connected" to "Connected",
        "disconnected" to "Disconnected",
        "status_secure" to "Connection is encrypted & secure",
        "status_not_connected" to "Your connection is unprotected",
        "select_server" to "Select Server",
        "optimal_server" to "Smart Fast Server",
        "upload_speed" to "Upload Speed",
        "download_speed" to "Download Speed",
        "upload" to "Upload",
        "download" to "Download",
        "total_upload" to "Total Upload",
        "total_download" to "Total Download",
        "connection_time" to "Connection Time",
        "ping" to "Ping",
        "ms" to "ms",
        "virtual_ip" to "Virtual IP",
        "protocol" to "Protocol",
        "settings" to "Settings",
        "language" to "App Language (زبان)",
        "persian" to "فارسی",
        "english" to "English",
        "kill_switch" to "Kill Switch",
        "kill_switch_desc" to "Block internet traffic if VPN drops unexpectedly",
        "split_tunneling" to "Split Tunneling",
        "split_tunneling_desc" to "Bypass domestic Iranian sites & banking apps",
        "dns_settings" to "DNS Settings",
        "auto_connect" to "Auto-connect on launch",
        "admin_panel" to "Admin Control Panel",
        "admin_panel_desc" to "Manage, import and update VPN configs",
        "admin_locked_tip" to "Enter Admin PIN code to access the management panel",
        "enter_pin" to "Admin PIN Authentication",
        "pin_placeholder" to "4-digit PIN (Default: 1234)",
        "unlock" to "Unlock Panel",
        "cancel" to "Cancel",
        "wrong_pin" to "Incorrect PIN code!",
        "admin_title" to "Admin Config Management",
        "add_new_config" to "Add New Config",
        "import_clipboard" to "Import from Clipboard",
        "config_name" to "Server / Config Name",
        "config_name_hint" to "e.g. Germany Ultra Speed #1",
        "config_url" to "Config Link / Code (VLESS/VMESS/SS/Trojan)",
        "config_url_hint" to "vless://... or vmess://... or ss://...",
        "country" to "Country",
        "flag" to "Flag",
        "protocol_type" to "Protocol Type",
        "expiration_date" to "Expiration (Days)",
        "save_config" to "Save Config",
        "edit_config" to "Edit Config",
        "delete" to "Delete",
        "delete_confirm" to "Are you sure you want to delete this config?",
        "test_ping" to "Test All Pings",
        "active_configs" to "Active Configs",
        "no_configs" to "No configs added yet. Add or import configs above.",
        "config_added_success" to "Config saved successfully",
        "config_deleted" to "Config removed",
        "expired" to "Expired",
        "active" to "Active",
        "change_admin_pin" to "Change Admin PIN",
        "new_pin" to "New PIN Code",
        "save_pin" to "Save PIN",
        "pin_changed" to "Admin PIN updated successfully",
        "secret_unlock_hint" to "Admin access unlocked!",
        "about" to "About ReNo VPN",
        "about_text" to "ReNo VPN is a high-speed, anti-censorship client with real-time speed monitoring and hidden admin configuration management.",
        "version" to "Version 1.0.0",
        "reset_defaults" to "Restore Default Servers",
        "speed_live" to "Live Speed Monitor",
        "all_servers" to "All Locations",
        "vip_servers" to "VIP Locations",
        "custom_servers" to "Admin Nodes",
        "auto_select" to "Auto Select (Smart)",
        "auto_select_desc" to "Automatically connects to the best low-traffic node",
        "antenna_green_desc" to "Low Traffic (Green - Fast)",
        "antenna_yellow_desc" to "Moderate Traffic (Yellow - 2 Bars)",
        "antenna_red_desc" to "Heavy Traffic (Red - 1 Bar)",
        "server_locked_title" to "Location Locked (VIP)",
        "server_locked_msg" to "This location is reserved for VIP members. 'Auto Select' is active and free for high-speed connection.",
        "locked" to "Locked",
        "unlocked" to "Free",
        "users_online" to "online users",
        "simulate_load" to "Toggle Traffic Load",
        "traffic_status" to "Network Load",
        "security_level" to "Encryption",
        "security_value" to "AES-256 + TLS",
        "kb_s" to "KB/s",
        "mb_s" to "MB/s",
        "latency_good" to "Excellent",
        "latency_medium" to "Good",
        "latency_poor" to "Fair",
        "secret_tap_hint" to "Tap logo 5 times to open hidden Admin Panel"
    )
}
